ghc:
  - 7.8

cache: 
  apt: true
  directories:
    - $HOME/.stack

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ed158bf029566cee4c0d
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

before_install:
  - sh .travis/install-stack.sh
  - sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch
  - stack --version
  - stack setup
  - stack install hpc-coveralls
  - export PATH="$HOME/.local/bin:$PATH"

script:
  - stack build
  - stack test
# Waiting on: https://github.com/commercialhaskell/stack/issues/222
  - find .
  - run-cabal-test --show-details=always

after_script:
  - hpc-coveralls --exclude-dir=tests kdb-haskell-tests
