language: haskell
ghc: 7.8.3

cache:
  directories:
  - ~/.cabal
  
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ed158bf029566cee4c0d
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch
  - cabal update
  - pushd .
  - cd ~/
  - travis_retry cabal install cabal-install
  - popd
  - cabal sandbox init
  - travis_retry cabal install hpc-coveralls --force-reinstalls

script:
  - cabal install --only-dependencies --enable-tests
  - cabal configure --enable-tests --enable-library-coverage
  - cabal build
  - run-cabal-test --show-details=always
#  - hlint src
#  - hlint tests
#  - hlint benchmarks

after_script:
  - hpc-coveralls --exclude-dir=tests kdb-haskell-tests