language: nix

matrix:
  fast_finish: true
  include:
    - env: GHCVER=ghcHEAD
    - env: GHCVER=ghc861
    - env: GHCVER=ghc844
    - env: GHCVER=ghc822
    - env: GHCVER=ghc802

  allow_failures:
    - env: GHCVER=ghcHEAD
    - env: GHCVER=ghc822
    - env: GHCVER=ghc802

before_install:
 - nix-channel --list
 - nix-channel --update

script:
 - nix-build --argstr compiler $GHCVER

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ed158bf029566cee4c0d
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

after_script:
  - nix-shell -p haskellPackages.hpc-coveralls --command 'hpc-coveralls --exclude-dir=tests kdb-haskell-tests'